### PR TITLE
Wrong resource name for repo resources

### PR DESCRIPTION
**Pull request by tobias-urdin**
The name for the repo resources is wrong and should be uchiwa and not sensu.

### CODE REVIEW

**Comment by solarkennedy** [comment]
We don't seem to use this variable? Can you confirm and remove it if true?

**Comment by tobias-urdin** [comment]
@solarkennedy It's used in the Package resource that installs the uchiwa package. See: https://github.com/Yelp/puppet-uchiwa/blob/master/manifests/install.pp#L44

**Comment by tobias-urdin** [comment]
To add more context, if you are managing the repo using this module your catalog wont even compile.
Error: Failed to apply catalog: Could not find dependency Apt::Source[sensu] for Package[uchiwa] at /etc/puppetlabs/code/modules/uchiwa/manifests/install.pp:42

**Comment by solarkennedy** [comment]
Whoa, gosh, I missed that.

Thanks!

**Pull request merged**
