### PR TITLE
Fixing Erroneous validations

### PR DESCRIPTION
**Pull request by magmax**
I'm using puppet 3.7.5-1puppetlabs1, and it failed because of the validations.

With this changes, validations pass

### CODE REVIEW

**Comment by solarkennedy** [comment]
Hmm. We could have caught this if we were testing against 3.7 I suppose.

How do you feel about augmenting your PR with new test targets so this is caught in the future?
(stealing from https://github.com/garethr/puppet-module-skeleton/blob/master/skeleton/.travis.yml)

**Comment by magmax** [comment]
I've never done that. I suppose I can try.

**Comment by magmax** [comment]
I misunderstood you: I was thinking you were talking about adding more tests.

Here there are the new environments. By the way: I'm having lot of trouble with the template. Maybe in other PR...

**Comment by solarkennedy** [comment]
Thanks!

**Pull request merged**
