### PR TITLE
Fixing template to work well with hiera

### PR DESCRIPTION
**Pull request by magmax**
Hello.

I'm trying to use this module with Hiera, and I have some problems. Indeed, I'm not sure this is ok, but I want to share it with you in order to get the best template for every usage. Maybe I'm using hiera in the wrong way.

Here you have an example of my hiera file:

```
uchiwa::install_repo: false
uchiwa::port: 3000
uchiwa::host: 0.0.0.0
uchiwa::user: sensu
uchiwa::pass: sensu
uchiwa::refresh: 30
uchiwa::api_config:
  localhost:
    port: 7654
    user: "%{rabbitmq::default_user}"
    pass: "%{rabbitmq::default_pass}"
    path: '/sensu'
uchiwa::sensu_api_endpoints:
  - basic:
    name: basic
    ssl: false
    insecure:  false
    host: 0.0.0.0
    port: 4567
    user: sensu
    pass: sensu
    timeout: 5
```

And it worked for me with this template, but no way to make it work with the current one.

### CODE REVIEW

**Comment by magmax** [comment]
Please, despite the test are passing, review the template to check if it likes you.

Thank you.

**Comment by solarkennedy** [comment]
You really shouldn't have to do this. The sensu::config class inherits the sensu class, allowing it to do all local variable lookups. (no scope() calls)

Can you paste in your manifest code as well?

**Comment by magmax** [comment]
My site.pp is:

```
node /^foo/ {
  # Workarround to failing: hiera_include('classes', [])
  hiera_array(classes, []).each | $name| { include($name) }
}
```

And the complete hiera file:

```
classes:
  - uchiwa
  
uchiwa::install_repo: false
uchiwa::port: 3000
uchiwa::host: 0.0.0.0
uchiwa::user: sensu
uchiwa::pass: sensu
uchiwa::refresh: 30
uchiwa::api_config:
  localhost:
    port: 7654
    user: "%{rabbitmq::default_user}"
    pass: "%{rabbitmq::default_pass}"
    path: '/sensu'
uchiwa::sensu_api_endpoints:
  - basic:
    name: basic
    ssl: false
    insecure:  false
    host: 0.0.0.0
    port: 4567
    user: sensu
    pass: sensu
    timeout: 5
```

**Comment by solarkennedy** [comment]
Hmm, I don't see any particular reason why this would not work. :(

**Comment by solarkennedy** [comment]
@magmax can you confirm this still doesn't work for you with master?

If not, can you try setting your hiera to use `uchiwa::params::port`, etc?

**Comment by magmax** [comment]
After all this time, I'm sure you are right.

I'm going to close this pull-request; the changeset will be there if we need it other day...

Thank you!

**Pull request closed without merging**
