### PR TITLE
Enable pam limits for su and add a ulimit for uchiwa user

### PR DESCRIPTION
**Pull request by KoeSystems**
Enable the ulimit for uchiwa user and set a default max memory used for process.

### CODE REVIEW

**Comment by pauloconnor** [comment]
I'd prefer to see this done upstream in the Uchiwa package https://github.com/sensu/uchiwa-build

**Comment by KoeSystems** [comment]
I agree. I've just done a PR to sensu/uchiwa-build if they merge it then I can just modify the uchiwa::config class to add the ulimit value to the /etc/default/uchiwa, that will be unlimited by default.

**Comment by solarkennedy** [comment]
@KoeSystems can you linke ot the PR? Has it been merged?

**Comment by KoeSystems** [comment]
The PR is https://github.com/sensu/uchiwa-build/pull/22

**Comment by solarkennedy** [comment]
I'm going to close this for now, we don't seem to need it anymore.

**Pull request closed without merging**
